#!/usr/bin/env bash
# Wrap vscode-fork/.build/electron/<nameLong>.app so Dock / double-click
# launches the real AIPiloty IDE instead of the blank Electron welcome page.
#
# code.sh already passes "." when started from make fork — those launches
# pass through unchanged. Bare launches (Dock pin of the Electron .app) get
# redirected to run-dev.sh.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AIPILOTY_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FORK_DIR="${FORK_DIR:-$AIPILOTY_ROOT/code-oss-ide/vscode-fork}"

if [[ ! -f "$FORK_DIR/product.json" ]]; then
  echo "No product.json at $FORK_DIR" >&2
  exit 1
fi

# Prefer node for nameLong; fall back to python
NAME_LONG=""
if command -v node >/dev/null 2>&1; then
  NAME_LONG="$(node -p "require('$FORK_DIR/product.json').nameLong" 2>/dev/null || true)"
fi
if [[ -z "$NAME_LONG" ]]; then
  NAME_LONG="$(python3 -c "import json; print(json.load(open('$FORK_DIR/product.json'))['nameLong'])" 2>/dev/null || true)"
fi
NAME_LONG="${NAME_LONG:-AIPiloty IDE}"

APP="$FORK_DIR/.build/electron/${NAME_LONG}.app"
MACOS="$APP/Contents/MacOS"
REAL="$MACOS/Electron.real"
WRAP="$MACOS/Electron"

if [[ ! -d "$APP" ]]; then
  echo "Electron app not found yet: $APP" >&2
  echo "Run make fork once so VS Code downloads Electron, then re-run this." >&2
  exit 0
fi

# First time: rename real binary
if [[ -f "$WRAP" ]] && [[ ! -f "$REAL" ]]; then
  # Only rename if it's a Mach-O binary (not our script)
  if file "$WRAP" | grep -q "Mach-O\|executable\|binary"; then
    mv "$WRAP" "$REAL"
  elif [[ ! -f "$REAL" ]]; then
    echo "Unexpected Electron file; skipping patch" >&2
    exit 0
  fi
fi

if [[ ! -f "$REAL" ]]; then
  echo "Missing Electron.real at $REAL" >&2
  exit 1
fi

# Always rewrite wrapper (paths may move)
cat > "$WRAP" <<EOF
#!/bin/bash
# AIPiloty Electron wrapper — do not edit; regenerated by scripts/patch-electron-app.sh
set -e
DIR="\$(cd "\$(dirname "\$0")" && pwd)"
REAL="\$DIR/Electron.real"

# Launch from code.sh / run-dev.sh already passes the vscode-fork dir as "."
if [[ "\$#" -gt 0 ]]; then
  exec "\$REAL" "\$@"
fi

# Dock / Finder double-click (no args) → start full AIPiloty IDE
export PATH="/opt/homebrew/bin:/usr/local/bin:\${HOME}/.local/bin:/usr/bin:/bin:\${PATH}"
if [[ -s "\${HOME}/.nvm/nvm.sh" ]]; then
  # shellcheck disable=SC1091
  source "\${HOME}/.nvm/nvm.sh" || true
fi

AIPILOTY="$AIPILOTY_ROOT"
LOG_DIR="\${HOME}/Library/Logs/AIPiloty"
mkdir -p "\$LOG_DIR"
exec /bin/bash "\$AIPILOTY/scripts/launch-desktop-ide.sh" >>"\$LOG_DIR/desktop-ide.log" 2>&1
EOF
chmod +x "$WRAP"

# Avoid macOS treating the wrapper as quarantine trash
xattr -cr "$APP" 2>/dev/null || true

echo "Patched: $APP"
echo "  Dock / double-click now starts AIPiloty IDE (not blank Electron)."
